spring:
  application:
    name: redis-sentinel-exporter
  redis:
    sentinel:
      # 集群名称
      master: mymaster
      # 哨兵节点地址
      nodes: 127.0.0.1:26380,127.0.0.1:26380,127.0.0.1:26381
    client-type: lettuce
server:
  port: 6390

# 指标采集周期
cron: "*/3 * * * * ?"